services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "4566:4566"
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: 1
      LS_LOG: DEBUG
      SERVICES: sqs,sns
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - ./tmp/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    container_name: mongodb
    networks:
      - cdp-tenant
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.runCommand({ping:1}).ok' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    command:
      ["mongod", "--replSet", "mongoRepl", "--bind_ip", "localhost,mongodb"]
    volumes:
      - mongodb-data:/data

  mongo-ready:
    image: mongo:6.0.13
    container_name: "mongo-ready"
    networks: [cdp-tenant]
    environment:
      PRIMARY: "mongodb:27017"
      REPLSET: "mongoRepl"
    volumes:
      - ./compose/wait-for-replicaset.sh:/wait-for-replicaset.sh:ro
    entrypoint: ["/bin/bash", "/wait-for-replicaset.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh 'mongodb://mongodb:27017/?directConnection=true' --quiet --eval 'db.hello().isWritablePrimary' | grep -q true || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 60

  entra:
    image: defradigital/fg-entra-stub-frontend:0.11.0
    ports:
      - "3010:3010"
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
