services:
  localstack:
    env_file:
      - ../fg-grants-core/compose/aws.env
    volumes:
      - ../fg-grants-core/tmp/localstack:/var/lib/localstack
      - ../fg-grants-core/compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack-core.sh
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:7.0
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    command: ["mongod", "--replSet", "mongoRepl", "--bind_ip_all"]

  mongo-ready:
    image: mongo:7.0
    volumes:
      - ./compose/wait-for-replicaset.sh:/wait-for-replicaset.sh:ro
    networks:
      - cdp-tenant
    environment:
      PRIMARY: "mongodb:27017"
      REPLSET: "mongoRepl"
      RS_HOST: "mongodb:27017"
    entrypoint: ["/bin/bash", "/wait-for-replicaset.sh"]

  # Move services onto cdp-tenant network so they can reach each other
  grants-ui:
    container_name: grants-ui
    profiles:
      - grants-ui
    networks:
      - cdp-tenant
    environment:
      GAS_API_URL: http://gas:3102
      GAS_API_AUTH_TOKEN: f081263c-6876-4d40-936f-ebdf63b5e893

  grants-ui-backend:
    profiles:
      - grants-ui
    networks:
      - cdp-tenant

  grants-ui-config-api:
    profiles:
      - grants-ui
    networks:
      - cdp-tenant

  fcp-defra-id-stub:
    profiles:
      - grants-ui
    networks:
      - cdp-tenant

  grants-ui-dal-stub:
    profiles:
      - grants-ui
    networks:
      - cdp-tenant

  mockserver:
    profiles:
      - grants-ui
    networks:
      - cdp-tenant

  gas:
    networks:
      - cdp-tenant
    environment:
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=mongoRepl
      AWS_ENDPOINT_URL: http://localstack:4566
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3102/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  fg-cw-backend:
    networks:
      - cdp-tenant
    environment:
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=mongoRepl
      OIDC_JWKS_URI: http://entra:3010/jwks
      AWS_ENDPOINT_URL: http://localstack:4566

  fg-cw-frontend:
    environment:
      NODE_ENV: development
      LOG_FORMAT: ecs

volumes:
  redis-data:
  mongodb-data:
  mongodb-config: